version: '3.8'
services:
  postfix:
    build: .
    ports:
      - "25:25"
    volumes:
      - ./config:/etc/postfix
      - postfix-data:/var/spool/postfix  # Mount volume for postfix data
    restart: always

volumes:
  postfix-data:  # Persistent storage for Postfix queues
