version: '3.8'
services:
  postfix:
    build: .
    container_name: postfix-local
    ports:
      - "1025:25"  
    volumes:
      - ./mail:/var/mail  
      - ./logs:/var/log
    restart: unless-stopped
